# Which upstream device to proxy Ubuntu tarballs from, and whether to replace
# the device and custom tarballs with locally provided files.
upstream:
    device: mako
    replaceDevice: false
    replaceCustom: false

#The ports can be overriden by the command line
#Disable HTTP or HTTPS by not providing a port for it
server:
    hostname: system-image.ubuntu.com
    httpPort:
    httpsPort: 443

#If present these enable HTTP Basic Acces Authentication
auth:
#    realm: example.com
#    username: user
#    password: pass

# imageserver -genChannels generates a channel.json containing all combinations
channels:
    channels: ["ubuntu-touch/vivid","ubuntu-touch/vivid-proposed"]
    devices: ["mako"]
